### ISSUE TITLE
Error when deploying related to S3 Tags

### ISSUE THREAD

**Issue by jasonumiker** [aws-samples/amazon-ecs-fullstack-app-terraform#5]
I got an error and my deployment of this failed - related to S3 Tags. When I Googled the error message I found this comment on the provider GitHub issue which looks like it is related to this repository - https://github.com/hashicorp/terraform-provider-aws/issues/19583#issuecomment-857645524

The way I got it to work was to comment out the default_tags in main.tf. 

Until the upstream bug is resolved I am considering PRing the commenting out of the default_tags so others don't this?

**Comment by Marinaburkhardt** [comment]
Hi Jason, thanks for raising this issue! Yes, that's right, that linked issue is related to this project. I ran into the same error in the past and got fixed by Hashicorp (apparently inconsistently). Reading the comments on the linked Issue it seems that multiple users keep having that problem for different aws services. A PR commenting that block could work as a temporary fix :)

**Comment by Marinaburkhardt** [comment]
Provider level tags were disabled, since we keep seeing inconsistencies when implementing them. See #16 for more details.
